
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Test Run

on:
  pull_request_target:
    branches:
      - main
      - features/*
      - release/*

jobs:
  setup:
    # name: Setup
    runs-on: ubuntu-latest
    environment: test
    # permissions:
    #   checks: write
      # contents: read
    steps:
      - name: Hello
        run: echo 1

      # - uses: LouisBrunner/checks-action@6b626ffbad7cc56fd58627f774b9067e6118af23 # v2.0.0
      #   with:
      #     token: ${{ github.token }}
      #     name: Test Run
      #     status: completed
      #     conclusion: ${{ job.status }}
      #     output: |
      #       {"summary":"Functional Test run completed. See links for more information.","title":"Functional Test Run"}
      #     details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      
